-- CREATE WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 300;

-- SET AS ACTIVE WAREHOUSE
USE WAREHOUSE COMPUTE_WH;

-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS DATA_ENGINEERING_SANDBOX;

-- CREATE SCHEMA
CREATE SCHEMA IF NOT EXISTS DATA_ENGINEERING_SANDBOX.NYPD_ARREST_DATA;

-- CREATE TABLE
CREATE OR REPLACE TABLE NYPD_ARRESTS (
    ARREST_KEY STRING,
    ARREST_DATE DATE,
    PD_CD INTEGER,
    PD_DESC STRING,
    KY_CD INTEGER,
    OFNS_DESC STRING,
    LAW_CODE STRING,
    LAW_CAT_CD STRING,
    ARREST_BORO STRING,
    ARREST_PRECINCT INTEGER,
    JURISDICTION_CODE INTEGER,
    AGE_GROUP STRING,
    PERP_SEX STRING,
    PERP_RACE STRING,
    X_COORD_CD INTEGER,
    Y_COORD_CD INTEGER,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
); 